
version: "3"

services:
  vote-test:
    image: ticicobresiserr/voting-app_vote:${VERSION}
    container_name: vote-test
    command: python app.py
    ports:
      - "5002:80"
    networks:
      - front-tier-test
      - back-tier-test

  result-test:
    image: ticicobresiserr/voting-app_result:${VERSION}
    container_name: result-test
    command: nodemon server.js
    ports:
      - "5003:80"
      - "5859:5858"
    networks:
      - front-tier-test
      - back-tier-test

  worker-test:
    image: ticicobresiserr/voting-app_worker:${VERSION}
    container_name: worker-test
    networks:
      - back-tier-test

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"
    ports: ["6379"]
    networks:
      - back-tier-test

  db-test:
    image: postgres:9.4
    container_name: db-test
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data-t"
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
    networks:
      - back-tier-test

volumes:
  db-data:

networks:
  front-tier-test:
  back-tier-test:
