
version: "3"

services:
  vote:
    image: ticicobresiserr/voting-app_vote:${VERSION}
    container_name: vote-test
    command: python app.py
    ports:
      - "5002:80"
    networks:
      - front-tier-test
      - back-tier-test

  result:
    image: ticicobresiserr/voting-app_result:${VERSION}
    container_name: result-test
    command: nodemon server.js
    ports:
      - "5003:80"
      - "5859:5858"
    networks:
      - front-tier-test
      - back-tier-test

  worker:
    image: ticicobresiserr/voting-app_worker:${VERSION}
    container_name: worker-test
    networks:
      - back-tier-test

  redis:
    image: redis:alpine
    container_name: redis-test
    ports: ["6380"]
    networks:
      - back-tier-test

  db:
    image: postgres:9.4
    container_name: db-test
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - back-tier-test

networks:
  front-tier-test:
  back-tier-test:
